"""Markdown tables generated from facts. Pages include these files; nobody types a row."""
from __future__ import annotations

from pathlib import Path

BANDS = ["D", "C", "B", "A", "AAA"]
HEADER = "<!-- GENERATED by wiki/facts/build_facts.py — do not edit. -->\n\n"


def _table(head: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(head) + " |", "|" + "|".join("---" for _ in head) + "|"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines) + "\n"


def band_table(t: dict[str, str]) -> str:
    return _table(["Band", "n", "Share", "Observed default rate", "Mean predicted PD",
                   "Observed / predicted"],
                  [[b] + [t[f"score.band.{b}.{c}"] for c in
                          ("n", "share", "observed", "predicted", "ratio")] for b in BANDS])


def population_table(t: dict[str, str]) -> str:
    names = {"everyone": "Everyone (the gate)", "booked": "Booked only",
             "rejected": "Rejected only"}
    return _table(["Population", "n", "Default rate", "Held-out AUC"],
                  [[names[p], t[f"score.pop.{p}.n"], t[f"score.pop.{p}.dr"],
                    t[f"score.pop.{p}.auc"]] for p in names])


def stress_table(t: dict[str, str]) -> str:
    return _table(["Scenario", "Columns", "Held-out AUC", "Gate"], [
        ["Committed card", f"all {t['score.n_features']}", t["score.auc_holdout"],
         "pass"],
        ["Bureau feed down", "drop " + t["score.stress.bureau_columns"],
         t["score.stress.no_bureau.auc"],
         "pass" if float(t["score.stress.no_bureau.auc"]) >= float(t["score.gate"]) else "**fail**"],
        ["Five raw columns", t["score.stress.five_raw_columns"], t["score.stress.five_raw.auc"],
         "pass" if float(t["score.stress.five_raw.auc"]) >= float(t["score.gate"]) else "**fail**"],
        ["Structural zeros only", t["score.stress.structural_five_columns"],
         t["score.stress.structural_five.auc"], "**fail**"],
        ["Revenue proxies only", t["score.stress.proxy_five_columns"],
         t["score.stress.proxy_five.auc"], "**fail**"],
    ])


def iv_table(t: dict[str, str]) -> str:
    feats = sorted((k.split(".", 2)[2] for k in t if k.startswith("score.iv.")),
                   key=lambda c: -float(t[f"score.iv.{c}"]))
    return _table(["Feature", "Information value", "Share of logit variance"],
                  [[f"`{c}`", t[f"score.iv.{c}"], t[f"score.var_share.{c}"]] for c in feats])


def ceiling_table(t: dict[str, str]) -> str:
    return _table(["", "Measured over", "AUC"], [
        ["Noise-free signal (the data's ceiling)", "all applicants", t["ceiling.signal_all"]],
        ["True PD, noise included", "all applicants", t["ceiling.truepd_all"]],
        ["Noise-free signal", "the scorecard's held-out 20%", t["ceiling.signal_holdout"]],
        ["Committed scorecard", "the same held-out 20%", t["score.auc_holdout"]],
        ["Gate", "", t["score.gate"]],
    ])


def adj_table(t: dict[str, str]) -> str:
    return _table(["Measure", "Value"], [
        ["Held-out AUC (gate)", f"{t['adj.auc']} ({t['adj.gate_auc']})"],
        ["Top-20% lift (gate)", f"{t['adj.lift']}× ({t['adj.gate_lift']}×)"],
        ["Approve if PD ≤", t["adj.t_low"]], ["Decline if PD ≥", t["adj.t_high"]],
        ["Decision mix (A / R / D)",
         f"{t['adj.mix.Approve']} / {t['adj.mix.Refer']} / {t['adj.mix.Decline']}"],
    ])


def fact_index(meta: dict[str, dict]) -> str:
    rows = [[f"`{k}`", d["text"], d["population"], f"`{d['source']}`"]
            for k, d in sorted(meta.items())]
    return ("---\ntitle: \"Every number in this documentation\"\n---\n\n" + HEADER +
            "Each value below is recomputed by `python verify.py`. Pages print these through "
            "`{{</* var key */>}}`; none is typed by hand.\n\n" +
            _table(["Key", "Value", "Population", "Source"], rows))


def render_all(t: dict[str, str], meta: dict[str, dict]) -> dict[str, str]:
    files = {
        "_generated/score-bands.md": band_table(t),
        "_generated/score-populations.md": population_table(t),
        "_generated/score-iv.md": iv_table(t),
        "_generated/score-ceiling.md": ceiling_table(t),
        "_generated/adj-headline.md": adj_table(t),
        "reference/facts.qmd": fact_index(meta),
    }
    if "score.stress.no_bureau.auc" in t:
        files["_generated/score-stress.md"] = stress_table(t)
    return {k: (v if k.endswith(".qmd") else HEADER + v) for k, v in files.items()}


def write_all(t: dict[str, str], meta: dict[str, dict], wiki_dir: Path) -> None:
    for rel, content in render_all(t, meta).items():
        p = wiki_dir / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)


def stale_files(expected: dict[str, str], wiki_dir: Path) -> list[str]:
    out = []
    for rel, content in expected.items():
        p = wiki_dir / rel
        if not p.exists() or p.read_text() != content:
            out.append(f"{rel}: generated file is stale (make wiki-facts)")
    return out


def stale(meta: dict[str, dict], wiki_dir: Path) -> list[str]:
    t = {k: d["text"] for k, d in meta.items()}
    return stale_files(render_all(t, meta), wiki_dir)
